* Getting my coding on (analysing reddit comments dataset) ^_^

** TODO Set-up database on external hard-drive
So far mariadb has been giving problems since the external hard-drive folder
doesn't have owner as mysql. This could be solve by:
 - Mounting drive as mysql user. Probably not a great solution.
 - Formatting drive to other file system (probably not great either...)

** TODO Get a blog post about this stuff going.
This would be a great first topic for the findingsignal blog. Maybe look into
using jupyter to post to wordpress?


<2017-08-09 Wed>
* Build an interactive widget involving graphics and differential equations
Something interesting to post to the blog. A fun way to get creative, and
share that with people.

** DONE Figure out best language for math behind it + visualizations
This will be paper.js. Can also easily be posted to blog (probably...)

** TODO Get started with paper.js

*** TODO Configure a minimal web development environment
https://italonascimento.github.io/configuring-a-basic-environment-for-javascript-development/

*** TODO Check out tutorial
http://andyshora.com/easy-paper-js-tutorial.html
http://paperjs.org/tutorials/

** Figure out how to post creations to blog
* Fix audio not working on WD15 dock :(
